steps:
  - label: "Install packages"
    command: npm install

  - label: "Test JS codes"
    command: npm run test

  - wait

  - label: "Create & upload docker image to AWS ECR"
    command: sh .buildkite/scripts/upload-docker-image.sh
