steps:
  - label: "Install packages"
    command: yarn & yarn test
    plugins:
      - docker-compose#v3.7.0:
          run: app
          config: docker-compose.yml

  - wait

  - label: "Create & upload docker image to AWS ECR"
    command: sh .buildkite/scripts/upload-docker-image.sh
