steps:
  - label: "Build"
    command: yarn

  - wait

  - label: "Test"
    command: yarn test

  - wait

  - label: "Create & upload docker image to AWS ECR"
    command: sh .buildkite/scripts/upload-docker-image.sh
